name: Repo Rater Action
run-name: on-issue-close (#${{ github.event.issue.number || github.event.pull_request.number }})

permissions:
  issues: write
  pull-requests: write

on:
  issues:
    types: [closed]
  pull_request:
    types: [closed]

jobs:
  on-issue-close:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          message: "Thank you for contributing to LinksHub! Please take a moment to explore the resource hub at https://linkshub.dev and and if you find it useful, don't forget to star ⭐ the repo!"
